global:
scrape_interval: 7s

scrape_configs:
  - job_name: "My app"
    metrics_path: /actuator/prometheus
    basic_auth:
      username: bob@gmail.com
      password: passBob
    static_configs:
      - targets: ["localhost:8080"]
